var annotated_dup =
[
    [ "AssignStatement", "class_assign_statement.html", "class_assign_statement" ],
    [ "ASTNode", "class_a_s_t_node.html", "class_a_s_t_node" ],
    [ "BinaryExpr", "class_binary_expr.html", "class_binary_expr" ],
    [ "BoolLiteral", "class_bool_literal.html", "class_bool_literal" ],
    [ "DoUntilStatement", "class_do_until_statement.html", "class_do_until_statement" ],
    [ "DoWhileStatement", "class_do_while_statement.html", "class_do_while_statement" ],
    [ "Environment", "class_environment.html", "class_environment" ],
    [ "Error", "class_error.html", "class_error" ],
    [ "Expr", "class_expr.html", "class_expr" ],
    [ "FloatLiteral", "class_float_literal.html", "class_float_literal" ],
    [ "ForStatement", "class_for_statement.html", "class_for_statement" ],
    [ "FunctionCall", "class_function_call.html", "class_function_call" ],
    [ "FunctionDefinition", "class_function_definition.html", "class_function_definition" ],
    [ "IfStatement", "class_if_statement.html", "class_if_statement" ],
    [ "InputStatement", "class_input_statement.html", "class_input_statement" ],
    [ "IntLiteral", "class_int_literal.html", "class_int_literal" ],
    [ "ListIndex", "class_list_index.html", "class_list_index" ],
    [ "ListLiteral", "class_list_literal.html", "class_list_literal" ],
    [ "PrintStatement", "class_print_statement.html", "class_print_statement" ],
    [ "RecursiveValue", "struct_recursive_value.html", "struct_recursive_value" ],
    [ "Refrence", "class_refrence.html", "class_refrence" ],
    [ "ReturnStatement", "class_return_statement.html", "class_return_statement" ],
    [ "StringLiteral", "class_string_literal.html", "class_string_literal" ],
    [ "Token", "struct_token.html", "struct_token" ],
    [ "TokenStream", "class_token_stream.html", "class_token_stream" ],
    [ "Type", "class_type.html", "class_type" ],
    [ "UnaryExpr", "class_unary_expr.html", "class_unary_expr" ],
    [ "VariableDeclaration", "class_variable_declaration.html", "class_variable_declaration" ],
    [ "WhileStatement", "class_while_statement.html", "class_while_statement" ]
];